site_name: Awesome Beancount
site_url: https://awesome-beancount.com
site_description: A curated list of resources for Beancount, which is a command-line based double-entry bookkeeping system.
site_author: Siddhant Goel
repo_url: https://github.com/siddhantgoel/awesome-beancount
theme:
    name: material
    palette:
        primary: indigo
    font: false
    custom_dir: overrides
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/siddhantgoel/awesome-beancount
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/siddhantgoel
nav:
    - "Plain Text Accounting using Python": README.md
