site_name: Awesome Beancount
site_url: https://awesome-beancount.com
site_description: A curated list of resources for Beancount, an open-source double entry bookkeeping system — ideal for plain text accounting users and Python software developers.
site_author: Siddhant Goel
repo_url: https://github.com/siddhantgoel/awesome-beancount
theme:
  name: material
  language: en
  palette:
    primary: indigo
  font:
    text: Roboto
  custom_dir: overrides
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/siddhantgoel/awesome-beancount
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@siddhantgoel
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/sgoel.dev
nav:
  - "Plain Text Accounting using Python": README.md
