site_name: Awesome Beancount
site_url: https://awesome-beancount.com
site_description: A curated list of resources for the Beancount command-line accounting system
site_author: Siddhant Goel
repo_url: https://github.com/siddhantgoel/awesome-beancount
